server:
  port: 8080
  host: ''
  mode: 'dev'

database:
  host: localhost
  port: 3306
  username: root
  password: 'root1234'
  name: scholar_ai
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

log:
  level: debug
  app_env: dev

mail:
  username: anhson.nguyen0307@gmail.com
  password: lfqs ljwy edja prwj
  smtp_host: smtp.gmail.com
  smtp_port: 587
